// generate-sitemap.ts — builds frontend/public/sitemap.xml from the real division
// list, so the sitemap can never drift out of sync with what /division/:id
// actually serves. Run via `npm run sitemap` (root) before every frontend build.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DIVISIONS } from '../src/data/divisions.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '../../frontend/public/sitemap.xml');

const SITE = 'https://warno-deck-randomizer.vercel.app';
const today = new Date().toISOString().slice(0, 10);

const urls: { loc: string; changefreq: string; priority: string }[] = [
  { loc: `${SITE}/`, changefreq: 'weekly', priority: '1.0' },
  { loc: `${SITE}/divisions`, changefreq: 'weekly', priority: '0.8' },
  ...DIVISIONS.map((d) => ({
    loc: `${SITE}/division/${d.id}`,
    changefreq: 'monthly',
    priority: '0.7',
  })),
];

const body = urls
  .map(
    (u) => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`,
  )
  .join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by backend/scripts/generate-sitemap.ts — do not hand-edit, run "npm run sitemap" instead. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${body}
</urlset>
`;

fs.writeFileSync(OUT, xml);
console.log(`Wrote ${urls.length} URLs -> ${path.relative(path.resolve(__dirname, '../..'), OUT)}`);
console.log(`  1 home + 1 divisions index + ${DIVISIONS.length} division pages`);